#服务器端口
server:
  port: 9333
spring:
  datasource:
    url: jdbc:mysql://myhost:3306/tuchong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
    timeout: 1000
    host: myhost
  cache:
    type: redis
    cache-names: redisCache, phoneUid, jwtCache, userCache

logging:
  level:
    com.example.securitydemo: debug
